/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register new user */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login user */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout current user */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Initiate Google OAuth */
        get: operations["googleRedirect"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google OAuth callback */
        get: operations["googleCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify email address */
        get: operations["verifyEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request password reset */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset password with token */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update profile */
        patch: operations["updateProfile"];
        trace?: never;
    };
    "/auth/user/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change password */
        patch: operations["changePassword"];
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List user accounts */
        get: operations["listAccounts"];
        put?: never;
        /** Create account */
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get account details */
        get: operations["getAccount"];
        put?: never;
        post?: never;
        /** Delete account */
        delete: operations["deleteAccount"];
        options?: never;
        head?: never;
        /** Update account */
        patch: operations["updateAccount"];
        trace?: never;
    };
    "/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List transactions */
        get: operations["listTransactions"];
        put?: never;
        /** Create transaction */
        post: operations["createTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/transfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create transfer between accounts */
        post: operations["createTransfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/bulk-categorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Bulk re-categorize transactions */
        patch: operations["bulkCategorize"];
        trace?: never;
    };
    "/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get transaction details */
        get: operations["getTransaction"];
        put?: never;
        post?: never;
        /** Delete transaction */
        delete: operations["deleteTransaction"];
        options?: never;
        head?: never;
        /** Update transaction */
        patch: operations["updateTransaction"];
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List categories */
        get: operations["listCategories"];
        put?: never;
        /** Create custom category */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete category */
        delete: operations["deleteCategory"];
        options?: never;
        head?: never;
        /** Update category */
        patch: operations["updateCategory"];
        trace?: never;
    };
    "/categories/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List auto-categorization rules */
        get: operations["listRules"];
        put?: never;
        /** Create auto-categorization rule */
        post: operations["createRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete rule */
        delete: operations["deleteRule"];
        options?: never;
        head?: never;
        /** Update rule */
        patch: operations["updateRule"];
        trace?: never;
    };
    "/budgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List budgets */
        get: operations["listBudgets"];
        put?: never;
        /** Create budget */
        post: operations["createBudget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budgets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete budget */
        delete: operations["deleteBudget"];
        options?: never;
        head?: never;
        /** Update budget */
        patch: operations["updateBudget"];
        trace?: never;
    };
    "/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dashboard summary */
        get: operations["getDashboardSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/spending-breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get spending by category */
        get: operations["getSpendingBreakdown"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get spending trends */
        get: operations["getSpendingTrends"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get signed URL for CSV upload */
        post: operations["getUploadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview CSV and detect columns */
        post: operations["previewImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start import with column mapping */
        post: operations["startImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get import status */
        get: operations["getImportStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import/{id}/duplicates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get flagged duplicates */
        get: operations["getImportDuplicates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import/{id}/resolve-duplicates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve duplicate decisions */
        post: operations["resolveDuplicates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List notifications */
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark notification as read */
        patch: operations["markNotificationRead"];
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark all notifications as read */
        patch: operations["markAllNotificationsRead"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            display_name: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
            /** @default false */
            remember: boolean;
        };
        AuthResponse: {
            user?: components["schemas"]["User"];
            message?: string;
        };
        LockedResponse: {
            message?: string;
            /** Format: date-time */
            locked_until?: string;
            minutes_remaining?: number;
        };
        ResetPasswordRequest: {
            token: string;
            /** Format: email */
            email: string;
            password: string;
            password_confirmation: string;
        };
        UpdateProfileRequest: {
            display_name?: string;
            /** Format: email */
            email?: string;
            notification_preferences?: {
                budget_alerts?: boolean;
                email_alerts?: boolean;
            };
        };
        ChangePasswordRequest: {
            current_password: string;
            password: string;
            password_confirmation: string;
        };
        User: {
            /** Format: uuid */
            id?: string;
            email?: string;
            display_name?: string;
            email_verified?: boolean;
            /** @enum {string} */
            subscription_tier?: "free" | "pro" | "team";
            notification_preferences?: Record<string, never>;
            /** Format: date-time */
            created_at?: string;
        };
        CreateAccountRequest: {
            name: string;
            /** @enum {string} */
            type: "checking" | "savings" | "credit_card" | "cash" | "investment";
        };
        UpdateAccountRequest: {
            name?: string;
        };
        Account: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** @enum {string} */
            type?: "checking" | "savings" | "credit_card" | "cash" | "investment";
            /** Format: decimal */
            balance?: number;
            currency?: string;
            is_asset?: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        CreateTransactionRequest: {
            /** Format: uuid */
            account_id: string;
            /** @enum {string} */
            type: "income" | "expense";
            /** Format: decimal */
            amount: number;
            /** Format: date */
            date: string;
            payee: string;
            /** Format: uuid */
            category_id?: string;
            notes?: string;
        };
        CreateTransferRequest: {
            /** Format: uuid */
            from_account_id: string;
            /** Format: uuid */
            to_account_id: string;
            /** Format: decimal */
            amount: number;
            /** Format: date */
            date: string;
            notes?: string;
        };
        UpdateTransactionRequest: {
            /** @enum {string} */
            type?: "income" | "expense";
            /** Format: decimal */
            amount?: number;
            /** Format: date */
            date?: string;
            payee?: string;
            /** Format: uuid */
            category_id?: string;
            notes?: string;
        };
        Transaction: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            account_id?: string;
            /** Format: uuid */
            category_id?: string;
            /** Format: uuid */
            linked_transaction_id?: string;
            /** @enum {string} */
            type?: "income" | "expense";
            /** Format: decimal */
            amount?: number;
            /** Format: date */
            date?: string;
            payee?: string;
            notes?: string;
            category?: components["schemas"]["Category"];
            account?: components["schemas"]["Account"];
            /** Format: date-time */
            created_at?: string;
        };
        PaginatedTransactions: {
            data?: components["schemas"]["Transaction"][];
            meta?: {
                current_page?: number;
                last_page?: number;
                per_page?: number;
                total?: number;
                /** @description Transactions hidden due to free tier limit */
                hidden_count?: number;
            };
        };
        CreateCategoryRequest: {
            name: string;
            /** Format: uuid */
            parent_id?: string;
            icon?: string;
        };
        UpdateCategoryRequest: {
            name?: string;
            icon?: string;
        };
        Category: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** Format: uuid */
            parent_id?: string;
            icon?: string;
            is_system?: boolean;
            is_protected?: boolean;
            subcategories?: components["schemas"]["Category"][];
        };
        CreateRuleRequest: {
            /** Format: uuid */
            category_id: string;
            pattern: string;
            /** @enum {string} */
            match_type: "contains" | "starts_with" | "equals";
            /** @default 0 */
            priority: number;
        };
        UpdateRuleRequest: {
            /** Format: uuid */
            category_id?: string;
            pattern?: string;
            /** @enum {string} */
            match_type?: "contains" | "starts_with" | "equals";
            priority?: number;
            is_active?: boolean;
        };
        AutoCategorizationRule: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            category_id?: string;
            pattern?: string;
            /** @enum {string} */
            match_type?: "contains" | "starts_with" | "equals";
            priority?: number;
            is_active?: boolean;
            category?: components["schemas"]["Category"];
        };
        CreateBudgetRequest: {
            /** Format: uuid */
            category_id: string;
            /** Format: decimal */
            amount: number;
            period_month: number;
            period_year: number;
            /** @default false */
            rollover_enabled: boolean;
            /** @default 80 */
            alert_threshold: number;
        };
        UpdateBudgetRequest: {
            /** Format: decimal */
            amount?: number;
            rollover_enabled?: boolean;
            alert_threshold?: number;
        };
        Budget: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            category_id?: string;
            /** Format: decimal */
            amount?: number;
            period_month?: number;
            period_year?: number;
            rollover_enabled?: boolean;
            /** Format: decimal */
            rollover_amount?: number;
            alert_threshold?: number;
            category?: components["schemas"]["Category"];
        };
        BudgetWithSpend: components["schemas"]["Budget"] & {
            /** Format: decimal */
            spent?: number;
            /**
             * Format: decimal
             * @description amount + rollover_amount
             */
            effective_budget?: number;
            /** Format: decimal */
            percent_used?: number;
            /** Format: decimal */
            remaining?: number;
        };
        DashboardSummary: {
            /** Format: decimal */
            net_worth?: number;
            /** Format: decimal */
            total_assets?: number;
            /** Format: decimal */
            total_liabilities?: number;
            current_month?: {
                /** Format: decimal */
                income?: number;
                /** Format: decimal */
                expenses?: number;
                /** Format: decimal */
                net?: number;
            };
            accounts?: components["schemas"]["Account"][];
        };
        SpendingBreakdown: {
            period?: {
                month?: number;
                year?: number;
            };
            /** Format: decimal */
            total?: number;
            categories?: {
                category?: components["schemas"]["Category"];
                /** Format: decimal */
                amount?: number;
                /** Format: decimal */
                percentage?: number;
            }[];
        };
        SpendingTrends: {
            months?: {
                month?: number;
                year?: number;
                label?: string;
                /** Format: decimal */
                income?: number;
                /** Format: decimal */
                expenses?: number;
                /** Format: decimal */
                net?: number;
            }[];
        };
        ImportPreview: {
            columns?: string[];
            sample_rows?: string[][];
            total_rows?: number;
            suggested_mapping?: {
                date?: number;
                amount?: number;
                payee?: number;
                category?: number;
                notes?: number;
            };
        };
        StartImportRequest: {
            file_key: string;
            /** Format: uuid */
            account_id: string;
            column_mapping: {
                date: number;
                amount: number;
                payee: number;
                category?: number;
                notes?: number;
            };
            /**
             * @default MM/DD/YYYY
             * @enum {string}
             */
            date_format: "MM/DD/YYYY" | "DD/MM/YYYY" | "YYYY-MM-DD";
        };
        ImportStatus: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            status?: "pending" | "processing" | "completed" | "failed";
            total_rows?: number;
            imported_count?: number;
            skipped_count?: number;
            error_count?: number;
            duplicate_count?: number;
            progress_percent?: number;
            errors?: {
                row?: number;
                message?: string;
            }[];
        };
        DuplicateTransaction: {
            row_index?: number;
            imported?: {
                /** Format: date */
                date?: string;
                amount?: number;
                payee?: string;
            };
            existing?: components["schemas"]["Transaction"];
        };
        Notification: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            type?: "budget_warning" | "budget_exceeded" | "import_complete" | "system";
            title?: string;
            message?: string;
            data?: Record<string, never>;
            /** Format: date-time */
            read_at?: string;
            /** Format: date-time */
            created_at?: string;
        };
    };
    responses: {
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message?: string;
                };
            };
        };
        /** @description Validation error */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message?: string;
                    errors?: {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
    parameters: {
        AccountId: string;
        TransactionId: string;
        CategoryId: string;
        BudgetId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User created, verification email sent */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Account locked (too many failed attempts) */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LockedResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    googleRedirect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to Google OAuth */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    googleCallback: {
        parameters: {
            query: {
                code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to app with session */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Email verified */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid or expired token */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Reset email sent (same response regardless of email existence) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Password reset successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid or expired token */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Profile updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["ValidationError"];
        };
    };
    listAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of accounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Account"][];
                    };
                };
            };
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description Account created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            /** @description Account limit reached (free tier) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["ValidationError"];
        };
    };
    getAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account deleted (with warning if had transactions) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message?: string;
                        transactions_deleted?: number;
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAccountRequest"];
            };
        };
        responses: {
            /** @description Account updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
        };
    };
    listTransactions: {
        parameters: {
            query?: {
                account_id?: string;
                category_id?: string;
                type?: "income" | "expense";
                date_from?: string;
                date_to?: string;
                /** @description Search payee name */
                search?: string;
                sort?: "date" | "-date" | "amount" | "-amount" | "payee" | "-payee";
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated transactions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTransactions"];
                };
            };
        };
    };
    createTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransactionRequest"];
            };
        };
        responses: {
            /** @description Transaction created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    createTransfer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransferRequest"];
            };
        };
        responses: {
            /** @description Transfer created (returns both transactions) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        from_transaction?: components["schemas"]["Transaction"];
                        to_transaction?: components["schemas"]["Transaction"];
                    };
                };
            };
        };
    };
    bulkCategorize: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    transaction_ids: string[];
                    /** Format: uuid */
                    category_id: string;
                };
            };
        };
        responses: {
            /** @description Transactions updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        updated_count?: number;
                    };
                };
            };
        };
    };
    getTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
        };
    };
    deleteTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTransactionRequest"];
            };
        };
        responses: {
            /** @description Transaction updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categories (system + user custom) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Category"][];
                    };
                };
            };
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryRequest"];
            };
        };
        responses: {
            /** @description Category created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    deleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CategoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category deleted, transactions reassigned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message?: string;
                        transactions_reassigned?: number;
                        budgets_deleted?: number;
                    };
                };
            };
            /** @description Cannot delete protected category */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CategoryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryRequest"];
            };
        };
        responses: {
            /** @description Category updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cannot modify system category */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of rules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["AutoCategorizationRule"][];
                    };
                };
            };
        };
    };
    createRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRuleRequest"];
            };
        };
        responses: {
            /** @description Rule created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutoCategorizationRule"];
                };
            };
        };
    };
    deleteRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rule deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRuleRequest"];
            };
        };
        responses: {
            /** @description Rule updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listBudgets: {
        parameters: {
            query?: {
                year?: number;
                month?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of budgets with spend data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["BudgetWithSpend"][];
                    };
                };
            };
        };
    };
    createBudget: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBudgetRequest"];
            };
        };
        responses: {
            /** @description Budget created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Budget"];
                };
            };
            /** @description Budget already exists for this category/period */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteBudget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BudgetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Budget deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateBudget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BudgetId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBudgetRequest"];
            };
        };
        responses: {
            /** @description Budget updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDashboardSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard summary data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
        };
    };
    getSpendingBreakdown: {
        parameters: {
            query?: {
                year?: number;
                month?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Spending breakdown */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpendingBreakdown"];
                };
            };
        };
    };
    getSpendingTrends: {
        parameters: {
            query?: {
                months?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Monthly spending trends */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpendingTrends"];
                };
            };
        };
    };
    getUploadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    filename: string;
                    /** @enum {string} */
                    content_type: "text/csv";
                };
            };
        };
        responses: {
            /** @description Signed upload URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        upload_url?: string;
                        file_key?: string;
                    };
                };
            };
        };
    };
    previewImport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    file_key: string;
                    /** Format: uuid */
                    account_id: string;
                };
            };
        };
        responses: {
            /** @description Column preview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportPreview"];
                };
            };
        };
    };
    startImport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartImportRequest"];
            };
        };
        responses: {
            /** @description Import started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        import_id?: string;
                        /** @enum {string} */
                        status?: "processing";
                    };
                };
            };
        };
    };
    getImportStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Import status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportStatus"];
                };
            };
        };
    };
    getImportDuplicates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Duplicate transactions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        duplicates?: components["schemas"]["DuplicateTransaction"][];
                    };
                };
            };
        };
    };
    resolveDuplicates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    decisions?: {
                        row_index?: number;
                        /** @enum {string} */
                        action?: "import" | "skip";
                    }[];
                };
            };
        };
        responses: {
            /** @description Duplicates resolved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listNotifications: {
        parameters: {
            query?: {
                unread_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of notifications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Notification"][];
                        unread_count?: number;
                    };
                };
            };
        };
    };
    markNotificationRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Marked as read */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    markAllNotificationsRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All marked as read */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
